
#
# This LookML file was generated by AtScale on 2025-11-12T23:26:47.048685154Z
#
# AtScale version: 2025.10.0
# Catalog: snowflake_usage_main

connection: "fl_test"
label: "snowflake_usage_main"


include: "/views/snowflake_usage_main/snowflake_usage_model.view.lkml"


explore: snowflake_usage_model {
  label: "snowflake_usage_model"
}

